version: '3'

services:
  backend:
    build:
      context: ./djangoProject
      dockerfile: Dockerfile
    container_name: django_app
    ports:
      - "8000:8000"
    volumes:
      - ./djangoProject/media:/app/media
    command: gunicorn djangoProject.wsgi:application --bind 0.0.0.0:8000 --workers 3 --timeout 120 --keep-alive 5

  frontend:
    build: ./frontend
    container_name: vue_app
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./djangoProject/media:/usr/share/nginx/html/media:ro

  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: blog
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_ROOT_HOST: "%"
      volumes:
      - mysql_data:/var/lib/mysql



volumes:
  mysql_data: