# Generated by Django 5.2.7 on 2025-11-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50, verbose_name='访客IP')),
                ('path', models.CharField(max_length=200, verbose_name='访问路径')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='浏览器信息')),
                ('visit_time', models.DateTimeField(auto_now_add=True, verbose_name='访问时间')),
            ],
        ),
    ]
