# Generated by Django 5.2.7 on 2025-11-24 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='QQ',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='QQ'),
        ),
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='message',
            name='QQ',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='QQ'),
        ),
        migrations.AddField(
            model_name='message',
            name='email',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='email'),
        ),
    ]
