# Generated by Django 5.2.7 on 2025-11-04 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0002_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bannedwords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField()),
            ],
        ),
    ]
