# Generated by Django 5.2.7 on 2026-02-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0002_comment_qq_comment_email_message_qq_message_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='imgs/')),
                ('md_file', models.FileField(upload_to='articles/%Y/%m/')),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('created_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(blank=True, to='blog_api.tag')),
            ],
        ),
    ]
