# Generated by Django 5.2.7 on 2026-02-13 12:33

import blog_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0003_tag_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('web_name', models.CharField(max_length=50)),
                ('name_avatar', models.ImageField(blank=True, null=True, upload_to=blog_api.models.avatar_upload_path)),
                ('about_md', models.TextField(blank=True)),
                ('footer_text1', models.CharField(blank=True, max_length=100)),
                ('footer_text2', models.CharField(blank=True, max_length=100)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=blog_api.models.article_cover_upload_path),
        ),
        migrations.AlterField(
            model_name='article',
            name='md_file',
            field=models.FileField(upload_to=blog_api.models.article_md_upload_path),
        ),
    ]
