# Generated by Django 5.2.7 on 2026-02-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0004_websetting_alter_article_cover_alter_article_md_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websetting',
            name='updated_time',
            field=models.DateTimeField(),
        ),
    ]
