# Generated by Django 5.2.7 on 2026-03-21 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0006_alter_comment_options_alter_comment_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
    ]
