# Generated by Django 5.2.7 on 2026-03-21 16:29

from django.db import migrations, models
import django.db.models.deletion


def migrate_article_data(apps, schema_editor):
    Comment = apps.get_model('blog_api', 'Comment')
    Article = apps.get_model('blog_api', 'Article')
    
    for comment in Comment.objects.all():
        # 获取原始的article字符串值
        # 由于article现在是ForeignKey，我们需要通过原始查询获取值
        # 使用cursor执行原始SQL
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(
                "SELECT article FROM blog_api_comment WHERE id = %s",
                [comment.id]
            )
            row = cursor.fetchone()
            if row:
                article_value = row[0]
                if article_value:
                    # 尝试根据标题查找文章
                    article = Article.objects.filter(title=article_value).first()
                    if article:
                        comment.article = article
                        comment.save()


def reverse_migrate(apps, schema_editor):
    # 回滚时将外键值转换回字符串（如果需要）
    # 但回滚可能不需要
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0008_alter_comment_article_nullable'),
    ]

    operations = [
        migrations.RunPython(migrate_article_data, reverse_migrate),
    ]