# Generated by Django 5.2.7 on 2026-03-21 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0009_migrate_comment_article_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('action_type', models.CharField(choices=[('login', '登录'), ('logout', '登出'), ('article_create', '创建文章'), ('article_update', '更新文章'), ('article_delete', '删除文章'), ('tag_create', '创建标签'), ('tag_update', '更新标签'), ('tag_delete', '删除标签'), ('comment_delete', '删除评论'), ('message_delete', '删除留言'), ('bannedword_create', '添加违禁词'), ('bannedword_delete', '删除违禁词'), ('websetting_update', '更新网站设置'), ('visitor_view', '查看访客统计'), ('other', '其他操作')], max_length=50, verbose_name='操作类型')),
                ('action_result', models.CharField(choices=[('success', '成功'), ('failure', '失败')], max_length=20, verbose_name='操作结果')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='用户代理')),
                ('target_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='目标模型')),
                ('target_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='目标ID')),
                ('target_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='目标名称')),
                ('details', models.JSONField(blank=True, null=True, verbose_name='操作详情')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作管理员')),
            ],
            options={
                'verbose_name': '管理员操作记录',
                'verbose_name_plural': '管理员操作记录',
                'ordering': ['-action_time'],
                'indexes': [models.Index(fields=['action_time'], name='blog_api_ad_action__3a86ce_idx'), models.Index(fields=['user', 'action_time'], name='blog_api_ad_user_id_1bcf7a_idx'), models.Index(fields=['action_type', 'action_time'], name='blog_api_ad_action__6fbe36_idx'), models.Index(fields=['action_result', 'action_time'], name='blog_api_ad_action__881e0c_idx')],
            },
        ),
    ]
