# Generated by Django 5.2.7 on 2026-03-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0010_adminauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_draft',
            field=models.BooleanField(default=False, verbose_name='是否为草稿'),
        ),
    ]
